from .day_1 import start_day_challenge
from .day_2 import start_day_challenge
from .day_3 import start_day_challenge
from .day_4 import start_day_challenge
from .day_5 import start_day_challenge
from .day_6 import start_day_challenge
from .day_7 import start_day_challenge
from .day_8 import start_day_challenge
from .day_9 import start_day_challenge
